"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 12:33:16.118630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('is_null_dacl', sa.Boolean(), nullable=False),
    sa.Column('has_explicit', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('group_members',
    sa.Column('group_sid', sa.String(length=184), nullable=False),
    sa.Column('member_sid', sa.String(length=184), nullable=False),
    sa.PrimaryKeyConstraint('group_sid', 'member_sid')
    )
    op.create_index(op.f('ix_group_members_member_sid'), 'group_members', ['member_sid'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_priority', 'jobs', ['status', 'priority', 'id'], unique=False)
    op.create_table('principals',
    sa.Column('sid', sa.String(length=184), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('dn', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('sid', sa.String(length=184), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_sid'), 'users', ['sid'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('acl_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acl_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=184), nullable=False),
    sa.Column('ace_type', sa.String(length=5), nullable=False),
    sa.Column('mask', sa.BigInteger(), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acl_id'], ['acls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_entries_acl_id'), 'acl_entries', ['acl_id'], unique=False)
    op.create_index(op.f('ix_acl_entries_sid'), 'acl_entries', ['sid'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('acl_id', sa.Integer(), nullable=True),
    sa.Column('owner_sid', sa.String(length=184), nullable=True),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acl_error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['acl_id'], ['acls.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_folders_parent_name')
    )
    op.create_index(op.f('ix_folders_acl_id'), 'folders', ['acl_id'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folders_share_id'), 'folders', ['share_id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('folders_seen', sa.Integer(), nullable=False),
    sa.Column('files_seen', sa.Integer(), nullable=False),
    sa.Column('files_added', sa.Integer(), nullable=False),
    sa.Column('files_updated', sa.Integer(), nullable=False),
    sa.Column('files_removed', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_sample', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_share_id'), 'scan_runs', ['share_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ctime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quick_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'name', name='uq_files_folder_name')
    )
    op.create_index(op.f('ix_files_content_hash'), 'files', ['content_hash'], unique=False)
    op.create_index(op.f('ix_files_extension'), 'files', ['extension'], unique=False)
    op.create_index(op.f('ix_files_folder_id'), 'files', ['folder_id'], unique=False)
    op.create_index(op.f('ix_files_mtime'), 'files', ['mtime'], unique=False)
    op.create_index(op.f('ix_files_share_id'), 'files', ['share_id'], unique=False)
    op.create_index('ix_files_size_hash', 'files', ['size', 'quick_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_size_hash', table_name='files')
    op.drop_index(op.f('ix_files_share_id'), table_name='files')
    op.drop_index(op.f('ix_files_mtime'), table_name='files')
    op.drop_index(op.f('ix_files_folder_id'), table_name='files')
    op.drop_index(op.f('ix_files_extension'), table_name='files')
    op.drop_index(op.f('ix_files_content_hash'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_scan_runs_share_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_folders_share_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_acl_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_acl_entries_sid'), table_name='acl_entries')
    op.drop_index(op.f('ix_acl_entries_acl_id'), table_name='acl_entries')
    op.drop_table('acl_entries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_sid'), table_name='users')
    op.drop_table('users')
    op.drop_table('shares')
    op.drop_table('principals')
    op.drop_index('ix_jobs_status_priority', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_group_members_member_sid'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_table('acls')
    # ### end Alembic commands ###
